### ISSUE TITLE
Consider support for comments

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox#1]
Running nose2 with planterbox-webdriver tests that include comments produces the following output:

```
(planterbox-webdriver)shawns-MacBook-Air:planterbox-webdriver shawn$ nose2
..............FE....F..F.
======================================================================
ERROR: I should see, I should not see (planterbox_webdriver.tests.test_webdriver:basics.feature)
# Forms stuff
# Requires known failure support
# Requires Multi-line step support
# alerts
#possible bug here?
# Requires known failure support
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shawn/source/planterbox-webdriver/lib/python2.7/site-packages/planterbox/__init__.py", line 242, in run_scenario
    step_fn, step_arguments = self.match_step(step)
  File "/Users/shawn/source/planterbox-webdriver/lib/python2.7/site-packages/planterbox/__init__.py", line 192, in match_step
    raise UnmatchedStepException()
UnmatchedStepException

======================================================================
FAIL: I should see, I should not see (planterbox_webdriver.tests.test_webdriver:basics.feature)
# Forms stuff
# Requires known failure support
# Requires Multi-line step support
# alerts
#possible bug here?
# Requires known failure support
----------------------------------------------------------------------
Scenario: Combo boxes fail
    Given I go to "basic_page"
    Then I should not see option "Mercedes" in selector "car_choice"
Traceback (most recent call last):
  File "/Users/shawn/source/planterbox-webdriver/lib/python2.7/site-packages/planterbox/__init__.py", line 246, in run_scenario
    step_fn(self, *step_arguments)
  File "/Users/shawn/source/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 414, in select_does_not_contain
    test.assertIsNone(option_in_select(test.world.browser, id_, option))
AssertionError: <selenium.webdriver.remote.webelement.WebElement object at 0x1098d8850> is not None

======================================================================
FAIL: I should see, I should not see (planterbox_webdriver.tests.test_webdriver:basics.feature)
# Forms stuff
# Requires known failure support
# Requires Multi-line step support
# alerts
#possible bug here?
# Requires known failure support
----------------------------------------------------------------------
Scenario: test labels
    When I go to "basic_page"
    And I click on label "Favorite Colors:"
    Then element with id "fav_colors" should be focused
    And element with id "bio_field" should not be focused
Traceback (most recent call last):
  File "/Users/shawn/source/planterbox-webdriver/lib/python2.7/site-packages/planterbox/__init__.py", line 246, in run_scenario
    step_fn(self, *step_arguments)
  File "/Users/shawn/source/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 286, in element_not_focused
    test.assertEqual(elem, focused)
AssertionError: <selenium.webdriver.remote.webelement.WebElement object at 0x1098d86d0> != <selenium.webdriver.remote.webelement.WebElement object at 0x1098f7ed0>

======================================================================
FAIL: I should see, I should not see (planterbox_webdriver.tests.test_webdriver:basics.feature)
# Forms stuff
# Requires known failure support
# Requires Multi-line step support
# alerts
#possible bug here?
# Requires known failure support
----------------------------------------------------------------------
Scenario: test date input
    When I go to "basic_page"
    And I fill in "dob" with "1900/01/01"
Traceback (most recent call last):
  File "/Users/shawn/source/planterbox-webdriver/lib/python2.7/site-packages/planterbox/__init__.py", line 246, in run_scenario
    step_fn(self, *step_arguments)
  File "/Users/shawn/source/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 235, in fill_in_textfield
    test.assertTrue(field, 'Can not find a field named "%s"' % field_name)
AssertionError: Can not find a field named "dob"

----------------------------------------------------------------------
Ran 25 tests in 29.038s

FAILED (failures=3, errors=1)
```

1.  Comments are echoed out which is a bit odd
2.  They are printed for each failing test 'report'

Comments can be useful and I've used them sparingly in lettuce-webdriver tests.  One useful example;

```
Scenario: 65. A Shared Page
        # This will fail every two weeks and need to be regenerated in steps.py
        ...
```

A comment like this can be useful if someone besides myself takes over test maintenance and is looking for information to why that particular test has started failing.

**Comment by npilon** [comment]
Addressed.
