### ISSUE TITLE
Planterbox does not support 'But' in step

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox#4]
In addition to words like, 'And', 'Given', 'Then', 'But' is typically supported.

https://github.com/cucumber/cucumber/wiki/Given-When-Then#and-but

Example use in a Scenario

```
Scenario: A Landing Page without Client Matter renders
        Given I sign in
        Then I should see "Welcome Enterprise Test" within 5 seconds
        But there should not be an element matching $(".fa-clock-o")
```

Fitst test uses, 'And', second, 'But';
```
(deus_lex) shawn@debian8 ~/source/deus_lex/winslow> nose2 -c unittest-sauce-law-stage.cfg winslow.tests.features:landing_page.feature:0 -v
Landing Page Permutations (winslow.tests.features:landing_page.feature:0)
Test each permutation of the Landing Page; ... ok

----------------------------------------------------------------------
Ran 1 test in 21.207s

OK
(deus_lex) shawn@debian8 ~/source/deus_lex/winslow> nose2 -c unittest-sauce-law-stage.cfg winslow.tests.features:landing_page.feature:0 -v
Landing Page Permutations (winslow.tests.features:landing_page.feature:0)
Test each permutation of the Landing Page; ... ERROR

======================================================================
ERROR: Landing Page Permutations (winslow.tests.features:landing_page.feature:0)
Test each permutation of the Landing Page;
----------------------------------------------------------------------
Scenario: A Landing Page without Client Matter renders
    Given I sign in
    Then I should see "Welcome Enterprise Test" within 5 seconds
    But there should not be an element matching $(".fa-clock-o")
Traceback (most recent call last):
  File "/home/shawn/source/planterbox/planterbox/__init__.py", line 196, in run_scenario
    step_fn, step_arguments = self.match_step(step)
  File "/home/shawn/source/planterbox/planterbox/__init__.py", line 136, in match_step
    raise UnmatchedStepException(step)
UnmatchedStepException:         But there should not be an element matching $(".fa-clock-o")

----------------------------------------------------------------------
```

**Comment by wholewheattoast** [comment]
@npilon i have a fix for this and will push in a moment.

**Comment by wholewheattoast** [comment]
@npilon see https://github.com/npilon/planterbox/pull/5

**Comment by npilon** [comment]
Merged.
