### ISSUE TITLE
First line of Scenario Outline reporting doesn't include details.

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox#8]
Given the following test;
```
Feature: Test for Testing
    Tests for testing
    
    Scenario Outline: Test if scenario outlines work properly
        And I point browser to "<url>"
        Then there should be an element matching $("<wait_condition>") within 5 seconds
        And I capture a screenshot
        
        Examples: 
            | page            | url                     | wait_condition  |
            | example         | https://www.example.com | .foo            |
            | another example | https://www.example.com | #bar            |
```

You'll get the following output.

```
(deus_lex) shawn@debian8 ~/source/deus_lex/winslow> nose2 -c ../qa_tool/webtests/planterbox.cfg -c ../qa_tool/webtests/sauce-shawn.cfg -c ../qa_tool/webtests/law-prod.cfg winslow.tests.features:test.feature:0 -v
Test for Testing (winslow.tests.features:test.feature:0)
    Scenario Outline: Test if scenario outlines work properly ... FAIL
Test for Testing (winslow.tests.features:test.feature:0)
    Scenario Outline: Test if scenario outlines work properly <- {u'': u'', u'url': u'https://www.example.com', u'wait_condition': u'#bar', u'page': u'another example'} ... FAIL

======================================================================
FAIL: Test for Testing (winslow.tests.features:test.feature:0)
Tests for testing
----------------------------------------------------------------------
Scenario Outline: Test if scenario outlines work properly
    And I point browser to "https://www.example.com"
    Then there should be an element matching $(".foo") within 5 seconds
Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/__init__.py", line 202, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/shawn/forks/planterbox-webdriver/planterbox_webdriver/css_selector_steps.py", line 89, in wait_for_element_by_selector
    test.assertTrue(elems)
AssertionError: [] is not true

======================================================================
FAIL: Test for Testing (winslow.tests.features:test.feature:0)
Tests for testing
----------------------------------------------------------------------
Scenario Outline: Test if scenario outlines work properly <- {u'': u'', u'url': u'https://www.example.com', u'wait_condition': u'#bar', u'page': u'another example'}
    And I point browser to "https://www.example.com"
    Then there should be an element matching $("#bar") within 5 seconds
Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/__init__.py", line 202, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/shawn/forks/planterbox-webdriver/planterbox_webdriver/css_selector_steps.py", line 89, in wait_for_element_by_selector
    test.assertTrue(elems)
AssertionError: [] is not true

----------------------------------------------------------------------
Ran 2 tests in 50.869s

FAILED (failures=2)
```

The second test includes the deatils of that particular scenario outline step `<- {u'': u'', u'url': u'https://www.example.com', u'wait_condition': u'#bar', u'page': u'another example'}` but the first does not.

**Comment by wholewheattoast** [comment]
Lilley result of https://github.com/npilon/planterbox/blob/master/planterbox/__init__.py#L243

**Comment by npilon** [comment]
This should be fixed on master.

**Comment by wholewheattoast** [comment]
Yep, looks good on master

![screen shot 2016-07-25 at 3 37 12 pm](https://cloud.githubusercontent.com/assets/231390/17119924/f0d56648-527d-11e6-88ae-f75299505c0d.png)
