### ISSUE TITLE
Bad scenario outline variables hang run

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox#9]
Running `(deus_lex) shawn@debian8 ~/source/deus_lex/winslow> nose2 -c ../qa_tool/webtests/shawn_sauce_windows_7_c44_law-stage.cfg  winslow.tests.features --plugin=nose2.plugins.mp -N=2 --log-level debug -v`

Nose2 / planterbox would hang.

running with `--log-level debug`

```
DEBUG:nose2.main:Internal Error
Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/nose2/main.py", line 265, in runTests
    self.result = runner.run(self.test)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/nose2/runner.py", line 53, in run
    executor(test, result)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/nose2/runner.py", line 41, in <lambda>
    executor = lambda suite, result: suite(result)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/unittest2/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/unittest2/suite.py", line 126, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/__init__.py", line 168, in run
    result=result,
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/__init__.py", line 248, in run_outline
    example_scenario = substitute_steps(scenario, example)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/__init__.py", line 432, in substitute_steps
    for step in scenario
KeyError: u'see_all_link'
Internal Error: runTests aborted: u'see_all_link'
```

Only seems to hang when running in parallel.

Resolving error (typo in variable) in scenario outline solved issue.

Possibly need to better catch exception in scenario outlines.

**Comment by npilon** [comment]
Should be addressed on master.
